classname=org.keybinder.wurm.KeybinderMod
classpath=keybinder.jar
sharedClassLoader=true
version=0.7.5
author=Chamomilo
skipIntroPage=false
language=en
centerViewAfterEmbark=true
queueMonitorSide=right
valuePackProvided=false
