classname=org.keybinder.wurm.KeybinderMod
classpath=keybinder.jar
sharedClassLoader=true
version=0.9.0
author=Chamomilo
updateProvider=chamomilo
updateCoordinatorProtocol=1
updateId=keybinder
updateName=Keybinder
updateRepo=chamomilo/wurm-keybinder
updateAsset=keybinder-{version}.zip
skipIntroPage=false
language=en
centerViewAfterEmbark=true
queueMonitorSide=right
valuePackProvided=false
